[graph]
targets = ["x86_64-pc-windows-msvc", "x86_64-unknown-linux-gnu"]

[licenses]
version = 2
allow = ["MIT", "Apache-2.0", "Apache-2.0 WITH LLVM-exception", "BSD-3-Clause", "Unicode-3.0", "CC0-1.0"]
confidence-threshold = 0.9

[[licenses.exceptions]]
crate = "opencrate-sdk"
allow = ["LicenseRef-OpenCrate-Community-1.0"]

[[licenses.clarify]]
crate = "opencrate-sdk"
expression = "LicenseRef-OpenCrate-Community-1.0"
license-files = [{ path = "LICENSE-OPENCRATE", hash = 0xd44aae0f }]

[[licenses.exceptions]]
crate = "oc-crypto"
allow = ["LicenseRef-OpenCrate-Community-1.0"]

[[licenses.clarify]]
crate = "oc-crypto"
expression = "LicenseRef-OpenCrate-Community-1.0"
license-files = [{ path = "LICENSE-OPENCRATE", hash = 0xd44aae0f }]

[bans]
multiple-versions = "deny"

[advisories]
version = 2
yanked = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
